### ISSUE TITLE
Error when blank

### ISSUE THREAD

**Issue by brianlorraine** [Itvisors/mendix-PivotTableWebWidget#3]
I'm using the SUM and when it has data it shows fine, but when I have no data yet I get this error

Pivot table widget pivotTableWebWidget1 has configuration errors
Cell value action sum is not allowed for cell data type string

**Comment by brianlorraine** [comment]
Once I put the pivot table inside something that had a page parameter context, now these are no longer greyed out. Howerver I don't see the point to them. I set the onclick action to a microflow and apparently the page parameter is the only thing that gets passed to the MF. What's the point of having an onclick event if I can't pass an object related to what you're clicking on.. the object.. a string ID... anything

**Comment by mgroeneweg** [comment]
> I'm using the SUM and when it has data it shows fine, but when I have no data yet I get this error
> 
> Pivot table widget pivotTableWebWidget1 has configuration errors Cell value action sum is not allowed for cell data type string

You cannot take a sum of strings!

**Comment by mgroeneweg** [comment]
> Once I put the pivot table inside something that had a page parameter context, now these are no longer greyed out. Howerver I don't see the point to them. I set the onclick action to a microflow and apparently the page parameter is the only thing that gets passed to the MF. What's the point of having an onclick event if I can't pass an object related to what you're clicking on.. the object.. a string ID... anything

The widget needs the context object. For the onclick action, the widget sets the ID values for the X and Y axis of the cell on the context object. Behind each cell there can be multiple values aggregated together, from Mendix objects or as result of the REST call.

Please read the documentation and try the sample project. As there is nothing wrong here I close the issue.

**Comment by brianlorraine** [comment]
The field I am SUMing on is NOT a string. It is a decimal. It works fine when there are records. However with no records, instead of displaying a message that there are no records, it gives this error.
