### ISSUE TITLE
CSV export is delimited by semicolons

### ISSUE THREAD

**Issue by brianlorraine** [Itvisors/mendix-PivotTableWebWidget#4]
I got the "Export to CSV" to work with a custom microflow, following the example project. For some reason, instead of commas, semicolon's ";" seperate the fields. Any idea what's up with that? I'm using UTF8 encoding. I've also tried "empty" for encoding.

**Comment by mgroeneweg** [comment]
It depends on locale settings. It started out as comma, as the name of the file type. However, that clashed with decimal values in many languages so the semicolon became the default. Excel will recognize it anyway, Google is your friend....
